# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2caf56a0889629c6adb1e8dfc631d66c630b3101cca595ce850a2fc70ba76c8dd432ee996a683506a4ef9f793aaf763aafd194f603fc80050e99d6533b319b8f

test:
  secret_key_base: b2d0005eccb20caded2283998201acca9299c78660fd86bf0ac5d10cac06397d13d91c73c6c4f04e1cff181408c8e4646d4dac087cef019bf546fb46e4dab654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
